Algoritmo "ex14"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/03/2016
Var  num1, num2, multi: real



Inicio

leia (num1)
leia (num2)

multi <- (num1+num2)

se (multi mod 2 = 0) entao
     escreva ("Multiplo")
senao
     escreva ("Não é multiplo")
fimse


Fimalgoritmo