algoritmo "semnome"
// Função :
// Autor :
// Data : 04/05/2016
// Seção de Declarações 
var
n1, n2, cont, soma: inteiro
inicio
escreval ("Informe n1")
leia (n1)
escreval ("Informe n2")
leia (n2)

soma <- 1

enquanto n1 > n2 faca
         se n1 mod 2 = 0 entao
            n1 <- n1 + soma
            se2 mod 2 = 0 entao
               n2 <- n2 + soma

            fimse
            fimse
            soma <- (n1 + n2) mod 2 = 0

fimenquanto

escreval (SOMA)

fimalgoritmo
