Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/04/2016
Var
// Seção de Declarações das variáveis 
num, cont, fat: inteiro

Inicio
escreval ("informe o numero")
leia (num)
cont <- 1
para fat <- 1 ate 4 faca
     cont <- cont * fat
fimpara
escreval (cont)


Fimalgoritmo