Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/04/2016
Var num, cont, i: inteiro


Inicio
escreval ("Informe a quantidade de numeros impares positivos:")
leia (num)
i <- 1
para cont <- 1 ate num faca
     escreva (i, " ")
     i <- i + 2
fimpara


Fimalgoritmo